[build]
command = "bun install && bun run build"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31556952, immutable"

[[plugins]]
package = "@netlify/plugin-nextjs"
